### ISSUE TITLE
How do you enable healthkit capacities?

### ISSUE THREAD

**Issue by chrisvidal** [gireeshp/fitness_challenge#9]
I tried to follow this
`Enable Healthkit in Capabilities tab in Xcode as shown here`

but the documentation does not match what I see on my xcode flutter project, how does this work please?

**Comment by gireeshp** [comment]
![image](https://user-images.githubusercontent.com/4717349/140823246-10b00a2f-97d1-4a9a-b051-d3fea1e60896.png)

When you open the runner, there's this "Signing & Capabilities" tab where you can click on "+Capability" button to add "Healthkit". Where exactly are you stuck? What are you seeing?

**Comment by chrisvidal** [comment]
thanks, I found it; I couldn't find this screen, as I didn't select "targets' and 'runner' below so I couldn't see the 'Signing Capabilities' tab.
thanks, it should be ok now, let me try to build
